name = "ovapi-stops"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]
LINES="GVB_22_1=30002061,GVB_48_2=30002012,GVB_5_2=30005077"
NODE_TLS_REJECT_UNAUTHORIZED="0"
WEATHER_LAT="52.22377"
WEATHER_LON="6.87236"

[[kv_namespaces]]
binding = "ovstops_weather"
id = "add binding id"
preview_id = "add preview binding id"